### PR TITLE
fontselect: overhaul font scoring and faux-ing

### LINKED ISSUE #437: Improve score-based font selection and faux-bold behavior
- We should match the score system described here: https://github.com/libass/libass/pull/362#issuecomment-705885810
- An additional caveat: if fsSelection bit 5 is set, faux-bold will never occur, and the font will not receive the 120-weight-point-equivalent score bonus for it
- Whether or not a font is italic (for the purposes of both faux-italic and scoring) is determined entirely by fsSelection bit 0 (ITALIC), whereas freetype also uses bit 9 (OBLIQUE)

Today someone ran into a font (Bona Nova) which has its regular variant at weight=300 and its bold at weight=400, with regular having fSelection=REGULAR and bold having fSelection=BOLD. This means that at \b400 the bold variant is selected, but at \b700 the _regular_ variant is selected, as the 120-point simulated-bold bonus pushes it closer to the requested weight than 400…
image
except that it doesn't seem to actually get faux-bolded in the output???? I'm not sure why that is. It seems like the glyph metrics are affected, but not the actual shapes:
image
…which probably means our emboldener is handling at least some cases wrong, since afaik we never touch metrics. I'm not completely sure what's going on here. Seems like Windows's emboldener either adjusts metrics or adjusts glyph forms, but not both??? This part needs further investigation.

Simpler VSFilter demo of the matching behavior; \b600 matches the Regular variant with faux-bold (400+120=520, which is a closer match for 600 than 700 is).
image

For a font family that contains a weight=700 variant with fsSelection=BOLD, `\b900` gives the same result as `\b700` (vs in libass, where `\b900` results in faux-bolding the bold). This is likely a regression in ac75f67697845efc1b0a15693c96dcc9e0f71518; we need to check _both_ conditions.

### PR DESCRIPTION
**Pull request by rcombs**
Fixes #437.

This emulates GDI's behavior, both around scoring and faux decisions.

The fontconfig provider doesn't provide the full information we'd need to handle this 100% accurately, so it's best-guessed.

This branch is on top of #676, basically just to avoid rebase issues.

### CODE REVIEW

**Comment by TheOneric** [comment]
Does this help with #305?

**Comment by rcombs** [comment]
No; I haven't yet determined why GDI sometimes fails to faux-bold when it nominally should (or does something weird with metrics instead, as seen in Bona Nova in #437).

**Comment by astiob** [comment]
It feels a bit weird to convert `fsSelection` to a custom bitmask in fontselect but use it raw in `ass_font_get_glyph`. Maybe `ass_face_get_fsSelection` should just be `ass_face_get_style_flags` returning the custom bitmask instead?

**Comment by rcombs** [comment]
Rebased with `ass_face_get_style_flags` returning the freetype mask constants. Might want to wait for #683?

**Comment by astiob** [comment]
Nice, thanks!

> Might want to wait for #683?

I was thinking of merging this first, because #683 makes all of this PR’s DirectWrite changes redundant—but you’ve put in some good effort into them and we might find it useful to have them in Git history later.

**Comment by moi15moi** [comment]
This should also close #613

File: libass/ass_directwrite_info_template.h [hunk 1]
```diff
@@ -12,12 +12,22 @@ static bool NAME(FONT_TYPE)(FONT_TYPE *font,
...
-                 (style == DWRITE_FONT_STYLE_OBLIQUE)? FONT_SLANT_OBLIQUE :
-                 (style == DWRITE_FONT_STYLE_ITALIC) ? FONT_SLANT_ITALIC : FONT_SLANT_NONE;
+    meta->style_flags = style == DWRITE_FONT_STYLE_NORMAL ? 0 : FT_STYLE_FLAG_ITALIC;
+
+    const char* data;
+    UINT32 size;
+    void* context;
+    hr = font->lpVtbl->TryGetFontTable(font, DWRITE_MAKE_OPENTYPE_TAG('O', 'S', '/', '2'),
+                                       &data, &size, &context, &exists);
+    if (!FAILED(hr)) {
```
Comment (moi15moi) [inline libass/ass_directwrite_info_template.h:24]: You should probably use [SUCCEEDED](https://learn.microsoft.com/en-us/windows/win32/api/winerror/nf-winerror-succeeded) instead of [!FAILED](https://learn.microsoft.com/en-us/windows/win32/api/winerror/nf-winerror-failed).

File: libass/ass_font.c [hunk 2]
```diff
@@ -548,6 +548,29 @@ int ass_face_get_weight(FT_Face face)
...
+}
+
+FT_Long ass_face_get_style_flags(FT_Face face)
+{
+    // If we have an OS/2 table, compute this ourselves, since FreeType
+    // will mix in some flags that GDI ignores.
+    TT_OS2 *os2 = FT_Get_Sfnt_Table(face, FT_SFNT_OS2);
+    if (os2)
+        return ass_fsSelection_to_style_flags(os2->fsSelection);
+
```
Comment (moi15moi) [inline libass/ass_font.c:570]: GDI also has another edge case.
If there is a [head](https://learn.microsoft.com/en-us/typography/opentype/spec/head) table, it will use the bold/italic of the mac_style.
If will help for mac font like in #679

**Review by astiob — APPROVED** [review]

File: libass/ass_fontselect.c [hunk 3]
```diff
@@ -445,21 +440,12 @@ ass_font_provider_add_font(ASS_FontProvider *provider,
     for (j = 0; j < meta->n_fullname; j++)
         printf("'%s' ", meta->fullnames[j]);
     printf("\n");
-    printf("  slant: %d\n", meta->slant);
+    printf("  style_flags: %x\n", (unsigned)meta->style_flags);
```
Comment (TheOneric) [inline libass/ass_fontselect.c:443]: Considering it’s `FT_Long`, `%lx` and `(unsigned long)` or perhaps to make sure even `%llx` and `(unsigned long long)` should be a better fit here

File: libass/ass_fontselect.c [hunk 4]
```diff
@@ -389,13 +385,12 @@ ass_font_provider_add_font(ASS_FontProvider *provider,
...
 {
     int i;
-    int weight, slant;
     ASS_FontSelector *selector = provider->parent;
     ASS_FontInfo *info = NULL;
     ASS_FontProviderMetaData implicit_meta = {0};
+    FT_Face face;
 
     if (!meta->n_family) {
-        FT_Face face;
```
Comment (TheOneric) [inline libass/ass_fontselect.c:400]: afaict `face` isn’t actually used outside of this `if` block (anymore)

**Review by TheOneric — APPROVED** [review]
just two small nits

File: libass/ass_fontselect.c (hunk 3 above)
Comment (astiob) [reply libass/ass_fontselect.c:443]: `%lx` and no cast should be enough IMO. `FT_Long` is [documented](https://freetype.org/freetype2/docs/reference/ft2-basic_types.html#ft_long) to be `signed long` and doesn’t seem subject to change. For comparison, FreeType also has `FT_Int32` and `FT_Int64`, whose underlying types are unspecified.

File: libass/ass_fontselect.c (hunk 4 above)
Comment (rcombs) [reply libass/ass_fontselect.c:400]: Reverted.

File: libass/ass_fontselect.c (hunk 3 above)
Comment (rcombs) [reply libass/ass_fontselect.c:443]: Done, and also:
- Changed the type of `style_flags` to within `ASS_FontInfo` to `FT_Long`
- Made `fsSelection_to_style_flags` static (it's no longer used outside `ass_font.c`)
